.TH WHISPER-SET-XFILESFACTOR 1
.SH NAME
whisper-set-xfilesfactor \- set xFilesFactor for existing whisper file.
.SH SYNOPSIS
.nf
.fam C
\fBwhisper-set-xfilesfactor\fP path xFilesFactor
.fam T
.fi
.SH DESCRIPTION
This command changes the xFilesFactor of the supplied whisper file, i.e. the fraction of data points in a propagation interval that must have known values for a propagation to occur.
.PP
The options are described below.
.SH OPTIONS
.TP
.B
\-h, \-\-help
Show the embedded help.
.SH AUTHOR
\fBwhisper\fP is a fixed size database, created by Chris Davis.
.PP
This manual page was written by Alexandre Rossi <niol@zincube.net>, for the Debian
project (but may be used by others).
